import os
import secret

TELEGRAM_API_TOKEN=secret.TELEGRAM_API_TOKEN
OWNER_ACTIVATION_TOKEN=secret.OWNER_ACTIVATION_TOKEN

SENSOR_PIN=4
BUFFER_TIME_STEPS=2
MAX_VIDEO_LENGTH=30

FILE_PATH=os.path.abspath(__file__).rsplit('/', 1)[0]
VIDEO_DIR='videos'
CAMERA_RECORDING_FORMAT='.h264'
CAMERA_CONVERTING_FORMAT='.mp4'

ACTIVATION_TOKEN_LENGTH=12
