import os
import secret

TELEGRAM_API_TOKEN=secret.TELEGRAM_API_TOKEN
OWNER_ACTIVATION_TOKEN=secret.OWNER_ACTIVATION_TOKEN

SENSOR_PIN=4
BUFFER_TIME_STEPS=2
MAX_VIDEO_LENGTH=30

FILE_PATH=os.path.abspath(__file__).rsplit('/', 1)[0]
VIDEO_DIR='videos'
CAMERA_RECORDING_FORMAT='.h264'
CAMERA_CONVERTING_FORMAT='.mp4'

OWNER_ROLE='OWNER_ROLE'
ADMIN_ROLE='ADMIN_ROLE'
MOD_ROLE='MODERATOR_ROLE'
SUB_ROLE='SUBSCRIBER_ROLE'
OPEN_ROLE='OPEN_ROLE'

REQUEST_TOKENS_ENABLED=False

TOKEN_LENGTH=12

ROLE_TO_RANK = {
    OWNER_ROLE: 4,
    ADMIN_ROLE: 3,
    MOD_ROLE: 2,
    SUB_ROLE: 1,
    OPEN_ROLE: 0
}

RANK_TO_ROLE = {
    4: OWNER_ROLE,
    3: ADMIN_ROLE,
    2: MOD_ROLE,
    1: SUB_ROLE,
    0: OPEN_ROLE
}

ROLES = {
    OWNER_ROLE: 'owner',
    ADMIN_ROLE: 'admin',
    MOD_ROLE: 'mod',
    SUB_ROLE: 'sub',
    OPEN_ROLE: 'open'
}

'''
TOKEN_OPTIONS = {
    '-a': ROLE_TO_RANK[ADMIN_ROLE],
    '-m': ROLE_TO_RANK[MOD_ROLE],
    '-s': ROLE_TO_RANK[SUB_ROLE]
}
'''

